@startuml
class SearchFilterTests {
    + 分次加入目錄條件_不符合條件的目錄應該不接受() : void
    + 分次加入目錄條件_符合條件的目錄應該被接受() : void
    + 分次加入副檔名條件_不符合條件的附檔名應該不接受() : void
    + 分次加入副檔名條件_符合條件的附檔名應該被接受() : void
    + 加入空的目錄排除條件_應該拋出例外() : void
    + 加入空的目錄接受條件_應該拋出例外() : void
    + 加入空的副檔名排除條件_應該拋出例外() : void
    + 加入空的副檔名接受條件_應該拋出例外() : void
    + 目錄先加入排除條件再加入接受條件_符合條件的目錄應該被接受() : void
    + 目錄先加入接受條件再加入排除條件_符合條件的目錄應該不被接受() : void
    + 目錄先批次加入排除條件再加入接受條件_符合條件的目錄應該被接受() : void
    + 目錄先批次加入接受條件再加入排除條件_符合條件的目錄應該不被接受() : void
    + 批次加入多個目錄接受條件_不符合條件的目錄應該不接受() : void
    + 批次加入多個目錄接受條件_符合條件的目錄應該被接受() : void
    + 批次加入多個副檔名接受條件_符合條件的附檔名應該被接受() : void
    + 批次加入空的目錄排除條件_應該拋出例外() : void
    + 批次加入空的目錄接受條件_應該拋出例外() : void
    + 批次加入空的副檔名排除條件_應該拋出例外() : void
    + 批次加入副檔名條件_只要有一個副檔名條件是空的_應該拋出例外() : void
    + 副檔名條件先加入排除條件再加入接受條件_符合條件的副檔名應該被接受() : void
    + 副檔名條件先加入接受條件再加入排除條件_符合條件的副檔名應該不被接受() : void
    + 副檔名條件先批次加入接受條件再加入排除條件_符合條件的副檔名應該不被接受() : void
    + 副檔名條件批次加入排除條件再加入接受條件_符合條件的副檔名應該被接受() : void
    + 副檔名條件批次加入接受條件再加入排除條件_符合條件的副檔名應該不被接受() : void
    + 當沒有條件時_任何副檔名都應該被接受(extension:string) : void
}
@enduml
