@startuml
class SearchFilter {
    + ExcludeDirectories(directories:string[]) : ISearchFilter
    + ExcludeDirectory(directory:string) : ISearchFilter
    + ExcludeExtension(extension:string) : ISearchFilter
    + ExcludeExtensions(extensions:string[]) : ISearchFilter
    + IncludeDirectories(directories:string[]) : ISearchFilter
    + IncludeDirectory(directory:string) : ISearchFilter
    + IncludeExtension(extension:string) : ISearchFilter
    + IncludeExtensions(extensions:string[]) : ISearchFilter
    + Match(files:IEnumerable<string>) : IEnumerable<string>
}
ISearchFilter <|-- SearchFilter
@enduml
